version: '2'
services:
    jenkins:
        build: ./jenkins
        ports:
            - "18080:8080"
            - "50000:50000"
        volumes:
            - ../volumes/jenkins/jenkins_home:/var/jenkins_home

#    nginx:
#        build: /nginx
#        port

