FROM debian:jessie
#RUN apt-get -y update
#RUN apt-get install -y openjdk-7-jre-headless
#RUN apt-get install -y default-jdk
#RUN apt-get install -y wget
#RUN wget http://pkg.jenkins-ci.org/debian-rc/binary/jenkins_2.0_all.deb
#RUN dpkg -i jenkins_2.0_all.deb
#RUN apt-get -f -y install
RUN /etc/init.d/jenkins start